[WIP] Add Travis-CI integration
klee/klee-uclibc pull request #11
Opened 2017-03-21 09:49 UTC by andreamattavelli

Added Travis-CI integration. The script is heavily based on the one used in KLEE.
The build script compiles and runs KLEE with the current build version of uclibc.

2017-03-21 16:07 UTC, andreamattavelli commented
I guess it's ready for your comments @delcypher @ccadar

2017-03-21 16:48 UTC, ccadar commented
Thanks, @andreamattavelli , this LGTM, and I think we should merge it even if we iterate over it later.  But I'll give others a chance to comment before merging it.

2017-03-22 12:45 UTC, delcypher commented
@andreamattavelli I mentioned in #10 that I would rather take the approach of triggering a rebuild of `klee/klee` when klee-uclibc is changed. I took a look at doing this by using [TravisCI's API for triggering rebuilds](https://docs.travis-ci.com/user/triggering-builds/).

It works but it has a few problems.

* Authorisation is required to triggered a rebuild which means an API key needs to be available. The API key cannot be public which means it needs to be stored in `.travis.yml` in an encrypted format. The encrypted data is not available in PRs which means during `klee/klee-uclibc` PRs we would not test `klee/klee`.
* Even if we could trigger a rebuild of `klee/klee` from a `klee/klee-uclibc` PR the build scripts wouldn't know where to pick up the modified version of klee-uclibc.

So in effect the approach I mention would only allow us to catch a problem once code in merged into klee/klee-uclibc's `master`.

Therefore for practical reasons I think building KLEE for klee-uclibc testing is the only thing we can do right now.

2017-03-22 12:55 UTC, delcypher requested changes
At a glance I think this a good starting point

We could save duplication though by cloning (a fixed version) the klee/klee repo and getting the `.travis` directory from there which has all the build scripts there. That way we can avoid duplicating the vast majority of the scripts.

2017-03-22 12:55 UTC, delcypher commented on .travis.yml
> +    global:
Please rip out these `secure`variables. Those are for coverage which we aren't doing here. If you change that the `global` key can be removed and we could also drop `matrix` and just have the list live underneath `env` like in https://docs.travis-ci.com/user/environment-variables#Defining-public-variables-in-.travis.yml

2017-03-22 12:55 UTC, delcypher commented on .travis.yml
> +    - LLVM_VERSION=3.4 SOLVERS=STP:Z3 STP_VERSION=2.1.2 DISABLE_ASSERTIONS=0 ENABLE_OPTIMIZED=1 USE_CMAKE=1
Drop STP and just use Z3. Our only concern real concern is klee-uclibc and STP has to be built from source. For Z3 we use a package so the build is faster.

2017-03-22 13:46 UTC, andreamattavelli commented
@delcypher I am really sorry, I quickly looked into the documentation and I figured it out immediately that it was not what we were looking for.
Still, it is interesting to trigger the rebuild in KLEE after we accept a PR, so to have an up-to-date Docker image. What do you think?

Thanks for you comments, I'll address them as soon as I have some free time.

2017-03-22 18:22 UTC, andreamattavelli commented
> We could save duplication though by cloning (a fixed version) the klee/klee repo and getting the .travis directory from there which has all the build scripts there. That way we can avoid duplicating the vast majority of the scripts.

Not really, I had to modify the vast majority of the paths in the scripts, since the location of KLEE and uclibc are different. The only unmodified files are `solvers.sh` and `stp.sh` (and we plan to remove STP..).

2017-03-22 18:22 UTC, andreamattavelli commented on .travis.yml
> +    - LLVM_VERSION=3.4 SOLVERS=STP:Z3 STP_VERSION=2.1.2 DISABLE_ASSERTIONS=0 ENABLE_OPTIMIZED=1 USE_CMAKE=1
Good point.

2017-03-23 09:09 UTC, andreamattavelli commented
@delcypher Addressed your comments.

2017-03-23 13:12 UTC, delcypher commented
@andreamattavelli 
> >We could save duplication though by cloning (a fixed version) the klee/klee repo and getting the .travis directory from there which has all the build scripts there. That way we can avoid duplicating the vast majority of the scripts.

> Not really, I had to modify the vast majority of the paths in the scripts, since the location of KLEE and uclibc are different. The only unmodified files are solvers.sh and stp.sh (and we plan to remove STP..).

Not building STP is just a change to the `SOLVERS` environment variable. I see your point about the different location of KLEE's sources and klee-uclibc but this something we could easily fix by generalising the build scripts so we tell them where the KLEE and klee-uclibc sources are.

Although what I'm suggesting is a bit more work we'll benefit in the long run because maintaining two different sets of very similar build scripts will be a pain. The build scripts are complicated (mostly because the legacy build system is garbage). The build also consumes these scripts so that will also benefit from this change.

2017-03-23 13:19 UTC, ccadar commented
I'm not against this change, but I would first merge what we have and improve later.  @delcypher , perhaps you can open a new issue with what you have in mind?

2017-03-23 22:19 UTC, delcypher commented
Merging early and then improving is fine with me.

2017-03-23 22:22 UTC, delcypher commented on .travis/klee.sh
> +source ${SRC_DIR}/.travis/testing-utils.sh
@andreamattavelli This is wrong. `testing-utils.sh` calls `exit 0` which means we don't build KLEE. You can see this in the output of the latest build --> https://travis-ci.org/klee/klee-uclibc/jobs/214164351

2017-03-23 22:32 UTC, andreamattavelli commented on .travis/klee.sh
> +source ${SRC_DIR}/.travis/testing-utils.sh
@delcypher Didn't you want faster builds? There you go!

2017-03-24 08:30 UTC, andreamattavelli commented
@ccadar @delcypher Fixed the last issue and squashed.

2017-03-24 11:07 UTC, ccadar commented
Great, since everyone is happy with this, let's merge it.

2017-03-24 11:07 UTC, merged